//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLBeneficiosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficios_Convenios
    {
        public int idBeneficio { get; set; }
        public int idConvênio { get; set; }
        public decimal Preço_Mensal { get; set; }
        public decimal Preço_Assinatura { get; set; }
        public bool Obrigatorio { get; set; }
    
        public virtual Beneficio Beneficio { get; set; }
        public virtual Convenio Convenio { get; set; }
    }
}
