//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLBeneficiosWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CLBeneficiosEntities : DbContext
    {
        public CLBeneficiosEntities()
            : base("name=CLBeneficiosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Associado> Associadoes { get; set; }
        public virtual DbSet<Beneficio> Beneficios { get; set; }
        public virtual DbSet<Beneficios_Convenios> Beneficios_Convenios { get; set; }
        public virtual DbSet<Convenio> Convenios { get; set; }
        public virtual DbSet<Convenio_Status> Convenio_Status { get; set; }
        public virtual DbSet<Grupo_Descontos> Grupo_Descontos { get; set; }
    }
}
